### ISSUE TITLE
Release v1.7-05b - jsa.np.npreader

### ISSUE THREAD

**Issue by ghost** [mdcao/japsa#13]
Hi,
In my hands the indicated release's version of npreader is failing to yield any output (but no error message), albeit with admittedly old versions of Metrichor fast5 file inputs (2D-MAP-005 workflow).  I can provide a small test dataset if necessary to reproduce the issue. Using Poretools is a still-functioning alternative so if you have moved on to focus on more recent file format versions then go ahead and close out this issue.

Thanks!

**Comment by hsnguyen** [comment]
Hi, thanks for considering npreader.
Yes because the fast5 file keeps changing for Metrichor, and we're moving to Albacore since Metrichor stopped providing free service so you can find npreader doesn't work with some of fast5 output. 

You can try out some older releases of npreader that could match your version. If that won't work out, feel free to send me (s.hoangnguyen@imb.uq.edu.au) some test data and I can take a look at it. 
Cheers,
